services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: facultyware
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

